spring.application.name=fl-backend

# PostgreSQL Railway Public
spring.datasource.url=jdbc:postgresql://interchange.proxy.rlwy.net:40015/railway?options=-c%20TimeZone%3DUTC
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.datasource.username=postgres
spring.datasource.password=NnIgAuPwjZfcbJRmAdVtwQdBWotWIJlb
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Web server
server.port=8080

# JWT
app.security.jwt.secret=federated-learning-super-secret-key-2024
app.security.jwt.expiration-seconds=3600
